root_path: "path_to_root"
worldfloods_folder: "dataset/WorldFloodsv2"
worldfloods_cnt: 0
include_osm: False
include_elevation: False
save_model_path: "models"
debug: True
progress_bar: True
device: "cuda:0"
exp_short_description: "baseline"
wandb_log: False

train:
  dataset_path: "dataset/train"
  model_ckpt: null
  num_workers: 0
  shuffle: True
  drop_last: True
  epochs: 25
  log_steps: 10
  patience: 100000

train_model:
  backbone: "timm-efficientnet-b5"
  pretrain: "imagenet"
  num_channels: 10

train_params:
  batch_size: 64
  learning_rate: 0.0001
  tile_size: 256  # Needs to be divisible by 4

val:
  dataset_path: "dataset/train"
  osm_path: "dataset/train/osm/9.geojson"
  save_val_outputs: True
  batch_size: 64
  num_workers: 0
  shuffle: False
  drop_last: False
  output_dir: "outputs_val"

test:
  dataset_path: "dataset/train"
  save_test_outputs: True
  model_ckpt: null
  batch_size: 64
  num_workers: 0
  shuffle: False
  drop_last: False
  output_dir: "outputs_test"
  